project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "State of the Art Machine Learning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Datasets
      - href: model.qmd
        text: Models
      - href: about.qmd
        text: About

format:
  html:
    theme: 
      light: cosmo
      dark: superhero
    css: styles.css
    toc: true



