project:
  type: website

website:
  title: "State of the Art Machine Learning"
  output-dir: docs
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: cosmo
      dark: superhero
    css: styles.css
    toc: true



